branding:
  icon: 'layers'
  color: 'blue'
  
  runs:
  using: "composite"
  steps:
    - name: echo test input
    shell: bash
    run: |
        echo "DM Thon lam ${{ env.DOCKER_IMAGE_NAME }}"
      
